services:
  mysql:
    image: mysql:8.0
    container_name: food-delivery-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456aA@"
      MYSQL_DATABASE: food_delivery
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456aA@"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
