// <auto-generated />
using FoodDelivery.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDelivery.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712051027_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FoodDelivery.Api.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "com",
                            Icon = "🍚",
                            Name = "Cơm"
                        },
                        new
                        {
                            Id = "pho-bun",
                            Icon = "🍜",
                            Name = "Phở & Bún"
                        },
                        new
                        {
                            Id = "pizza",
                            Icon = "🍕",
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = "ga-ran",
                            Icon = "🍗",
                            Name = "Gà rán"
                        },
                        new
                        {
                            Id = "tra-sua",
                            Icon = "🧋",
                            Name = "Trà sữa"
                        },
                        new
                        {
                            Id = "an-vat",
                            Icon = "🍢",
                            Name = "Ăn vặt"
                        },
                        new
                        {
                            Id = "do-chay",
                            Icon = "🥗",
                            Name = "Đồ chay"
                        },
                        new
                        {
                            Id = "trang-mieng",
                            Icon = "🍰",
                            Name = "Tráng miệng"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
